### ISSUE TITLE
Releases for 1.8.0 and 1.8.2 do not contain the compiled SDK

### ISSUE THREAD

**Issue by silid** [Lawo/ember-plus#104]
The releases for the SDK 1.8.0 and 1.8.2 do not contain the compiled SDK but the compiled EmberPlusViewer.

The 1.6.2 release does contain the compiled SDK and tools etc.

**Comment by KimonHoffmann** [comment]
Yes, with the exception of the Ember+ Viewer, which is only available in binary form, we no longer provide precompiled tools and/or libraries.

Building either locally should be trivial, now that the libraries come with proper Cmake build descriptions.
