### ISSUE TITLE
LAWO - MC²56 MKIII - Ember+ protocol - No Label layers available after a get directory

### ISSUE THREAD

**Issue by yboujraf** [Lawo/ember-plus#106]
Dear @KimonHoffmann 

I already posted an issue to Lawo ticketing but when I talk about EmberPlusViewer as tools and crashes they send to github ;-)

I am using the Ember+ lib from Lawo and when I am asking a get Directory for the matrix node, I receive the path for the label layer and could make crosspoint with success.

**Regarding label layers :**

The label layers are declared in the emberTree structure. But unfortunately
, those paths didn't exist in the EmberTree structure that's why EmberPlusViewer crashed each time I 'd like to change the label layer.

This is a copy of the EmberTree Structure discovered :

```
        {
            "path": "819640",
            "isOnline": true,
            "identifier": "_4",
            "description": "Matrices",
            "children": [
                {
                    "number": 819641,
                    "isOnline": true,
                    "identifier": "_1",
                    "description": "Global Matrices",
                    "children": [
                        {
                            "number": 819642,
                            "type": 2,
                            "mode": 0,
                            "identifier": "_0",
                            "description": "Audio Matrix",
                            "targetCount": 2392,
                            "sourceCount": 2152,
                            "maximumConnectsPerTarget": 1,
                            "maximumTotalConnects": 2392,
                            "parametersLocation": "819640.819641.819642.2",
                            "labels": [
                                {
                                    "basePath": "819640.819641.819642.1.0",
                                    "description": "Label 0"
                                },
                                {
                                    "basePath": "819640.819641.819642.1.1",
                                    "description": "Label 1"
                                },
                                {
                                    "basePath": "819640.819641.819642.1.2",
                                    "description": "Label 2"
                                },
                                {
                                    "basePath": "819640.819641.819642.1.3",
                                    "description": "Label 3"
                                },
                                {
                                    "basePath": "819640.819641.819642.1.4",
                                    "description": "Label 4"
                                }
                            ],
```

[test-discover_path_3.zip](https://github.com/Lawo/ember-plus/files/4189765/test-discover_path_3.zip)

**EmberPlusViewer - Get Labels**

The EmberPlusViewer discovered the number of layers but finally nothing in the EmberTree

<img width="697" alt="Snag_3618974" src="https://user-images.githubusercontent.com/6151258/74301880-ca02e380-4d54-11ea-834f-a7f7bbe9c9d4.png">

<img width="731" alt="Snag_3612e82" src="https://user-images.githubusercontent.com/6151258/74301860-bc4d5e00-4d54-11ea-9021-fad3d3f86709.png">

A dumfile is generated and added in this issue

[EmberPlusView crashed.2020-02-12 04-49.zip](https://github.com/Lawo/ember-plus/files/4189766/EmberPlusView.crashed.2020-02-12.04-49.zip)

**Conclusion :** 

How to know the label of each source & target for each matrix available in the MC² or Nova73HD ?

Thanks if you could highlighting me how to get the label layers with Ember+

Best Regards,
Youssef

**Comment by mywave82** [comment]
(According to the standard, the branch to contains the labels, can be "invisible" when walking the tree, but must accessible when requested directly.)

**Comment by yboujraf** [comment]
Dear @mywave82 

I Will try it and back to you, thanks for your comment.

Boujraf Youssef

**Comment by yboujraf** [comment]
Dear @mywave82 

After reading the latest ember+ specification https://github.com/Lawo/ember-plus/blob/master/documentation/Ember%2B%20Documentation.pdf

What you refer is only for the **ParametersLocation**

![image](https://user-images.githubusercontent.com/6151258/74339147-c5b1e700-4da3-11ea-8cac-ff21b3737b65.png)

I will check with my developer when expanding the emberTree structure to check the QualifiedMatrix properties, if **Labels** is defined and **basepath** 
- if the labels path are already existing during the expand do nothing
- if no path discovered in the EmberTree do the GetDirectory for each label path layer and add it in the EmberTree.

Regarding the tyniEmberPlusRouter, the label layer is included in the EmberTree

[test-discover-tinyember-with-label-description.zip](https://github.com/Lawo/ember-plus/files/4192717/test-discover-tinyember-with-label-description.zip)

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear @mywave82 

After a getDirectory from the basepath (Layer), it works, I can retrieve the labels ;-)

Best Regards,
Youssef
