### ISSUE TITLE
Missing exported functions of libember_slim for Windows DLL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Lawo/ember-plus#30]
```
No functions are exported if the libember_slim library is build in the Windows 
DLL variant.


```

Original issue reported on code.google.com by `nullable...@gmail.com` on 2 Dec 2014 at 12:48

**Comment by mkeuck** [comment]
Function exports were added with commit [added LIBRARY_API declarations for all functions](https://github.com/Lawo/ember-plus/commit/16f4a36918ad7594dbabae038cbda3dbb3b27afa#diff-c0943baa35e4de8af786aadf309d44f3) (16f4a36)
