### ISSUE TITLE
Patch for /trunk/EmberLib.net/EmberPlusWalk/GlowEndPoint.cs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Lawo/ember-plus#34]
```
Fixed NullReferenceException in GlowReader_RootReady.
```

Original issue reported on code.google.com by `julien.m...@gmail.com` on 19 Feb 2015 at 2:27

Attachments:
* [GlowEndPoint.cs.patch](https://storage.googleapis.com/google-code-attachments/ember-plus/issue-34/comment-0/GlowEndPoint.cs.patch)

**Comment by jv42** [comment]
[I'm the author of the original issue on Google Code]

Should we create pull requests on GitHub now, I mean, would they be reviewed and integrated?

**Comment by KimonHoffmann** [comment]
Hei!

Yes, that would be awesome. :) A pull request would be greatly appreciated!

**Comment by jv42** [comment]
I've created a PR with that fix and another occurrence of the same error fixed: https://github.com/Lawo/ember-plus/pull/36

**Comment by KimonHoffmann** [comment]
Closing as this issue is now a duplicate of #36.
