### ISSUE TITLE
libember_slim does not invoke callback when the node is empty

### ISSUE THREAD

**Issue by astedler** [Lawo/ember-plus#38]
using libember_slim i encountered the following problem:
When traversing a tree using GETDIR i keep track of all requests send and remove it from the list as soon as i got an appropriate answer.
Unfortunately when a device has an empty node and generates for example:
<code>0x60 0x80 0x6b 0x80 </code>
<code>    0xa0 0x80 0x6a 0x80 </code>
<code>        0xa0 0x04 0x0d 0x02 0x01 0x03 </code>
<code>    0x00 0x00 0x00 0x00 </code>
<code>0x00 0x00 0x00 0x00</code>
which is a correct answer for an empty node the libember_slim does not invoke a callback due to the fact that there is nothing set inside the node.

Unfortunately it is not distinguishable to the device NOT answering at all from my point of view because no callback is fired (except onPackageReceived(...) )
Therefore the condition that keeps track of treewalking never got signalled (except due to timeout)

But If the provider includes let us say the online flag in the answer like:
<code>0x60 0x15 0x6b 0x13                  ; </code>
<code>    0xa0 0x11 0x6a 0x0f               ; Qualified Node</code>
<code>        0xa0 0x04 0x0d 0x02 0x01 0x03 ; Path= 01,03</code>
<code>        0xa1 0x07 0x31 0x05           ; Online Property</code>
<code>            0xa3 0x03 0x01 0x01 0xff  ;  BOOLEAN: true</code>
everything works fine

it is important that libember_slim invokes the callback on nodes which are empty to keep track of treewalking

**Comment by astedler** [comment]
Just in case anyone is stumbling about the comments in the code above... 
correctly it is:
```
0x60 - Application | Container +  0 (Root)                      , 0x15 - length,
0x6b - Application | Container + 11 (RootElementCollection)     , 0x13 - length,
0xa0 - Context     | Container +  0 (Default Element)           , 0x11 - length,
0x6a - Application | Container + 10 (QualifiedNode)             , 0x0f - length,
0xa0 - Context     | Container +  0 (Default Element)           , 0x04 - length,
0x0d - Universal               + 13 (Relative Object)           , 0x02 - length,
0x01, 0x03 - data,
0xa1 - Context     | Container +  1 (Contents)                  , 0x07 - length,
0x31 - Universal   | Container + 17 (Set)                       , 0x05 - length,
0xa3 - Context     | Container +  3 (isOnline)                  , 0x03 - length,
0x01 - Universal               +  1 (Boolean)                   , 0x01 - length,
0xff - data
```

**Comment by mkeuck** [comment]
Hi Arndt,
I will take a look into this. I am not that familiar with the C implementation of the library. But as long as a node object is reported, it should be possible to invoke the callback as well.

**Comment by astedler** [comment]
I have attached the neccessary patch to get even empty nodes; for there was no callback at all making it impossible to distinguish between an empty node and one without content.

[patch1.txt](https://github.com/Lawo/ember-plus/files/1348079/patch1.txt)
[patch2.txt](https://github.com/Lawo/ember-plus/files/1348080/patch2.txt)
[patch3.txt](https://github.com/Lawo/ember-plus/files/1348082/patch3.txt)

**Comment by astedler** [comment]
Arghhh...
Unfortunately I found two more ...issues... concerning that libember-slim does a callback when the contents of something( like node, parameter, function) is ready and not when the element itself is ready.
When the provider answers with a node and an empty children-set within, my patch will not cover it...
I had rework it and i am testing it right now.
You must take the upper level of the stack into account when  you do a callback and 'remember' whether you did one before or not.

**Comment by KimonHoffmann** [comment]
Hi Arndt!

Any info on that? Have you completed testing of the corrected patch?
