### ISSUE TITLE
Bug in libember StreamBuffer::clear()

### ISSUE THREAD

**Issue by 4ca** [Lawo/ember-plus#48]
If the StreamBuffer is used to encode a large Glow tree into an S101 message with multiple packets of a given maximum size, two packets will be created, the first with the specified length, the second will be the length of all the remaining data. This is due to the StreamBuffer's clear function not clearing the internal buffer correctly.

Current version:-
    template<typename ValueType, unsigned short ChunkSize>
    inline void StreamBuffer<ValueType, ChunkSize>::clear()
    {
        **StreamBuffer empty();**
        swap(empty);
    }

Suggested solution:-
    template<typename ValueType, unsigned short ChunkSize>
    inline void StreamBuffer<ValueType, ChunkSize>::clear()
    {
        **StreamBuffer empty(max_size());**
        swap(empty);
    }

**Comment by KimonHoffmann** [comment]
Hi!

Thanks for spotting this. You you provide us with a pull request with the proposed fix applied?

Thanks in advance and best regards,
  Kimon
