### ISSUE TITLE
libember_slim - ber.c - ber_decodeReal(...) malfunction

### ISSUE THREAD

**Issue by astedler** [Lawo/ember-plus#50]
When an ember provider offers the (real-)value NaN in form like:
0xa2 0x03 0x09 0x01 0x42 
(this is a real example taken from the V__link4 using libember_slim to encode NaN)
the libember_slim is not able to decode it...

Patch see attachment...
[ber_decodeReal-snippet.txt](https://github.com/Lawo/ember-plus/files/508376/ber_decodeReal-snippet.txt)

**Comment by KimonHoffmann** [comment]
Hi!

Thanks for discovering this and reporting it as a defect. Could you please create a pull request with you fix and without any commented out code so that we can merge it into master?

Thanks in advance and best regards!

**Comment by KimonHoffmann** [comment]
Hi again!

I see you created your own fork including said patch. Could you please make this a PR with an appropriate comment referring to this issue?

Thanks again and best regards!
