### ISSUE TITLE
Unclear Documentation for use of factor in conjunction with minimum and maximum

### ISSUE THREAD

**Issue by astedler** [Lawo/ember-plus#51]
If factor is set, the value given by the provider must be displayed by the consumer dividing _value_ by _factor_ (which then mght change from INTEGER to REAL...
But how to handle the _minimum_ and _maximum_ properties?
Shall i assume the they are also multiplied by _factor_, so that i can compare the _value_ to _minimum_ and _maximum_ to check whether it is valid or not, or do i have to assume _minimum_ and _maximum_ are given as values already devided by _factor_ and i have to check **minimum <= value/factor <= maximum**?

???

**Comment by mkeuck** [comment]
Hi,
the parameter properties Value, DefaultValue, Minimum and Maximum shall always be reported in the same unit. So you have to divide all of them by the factor or apply a formula (if provided) to them.

**Comment by KimonHoffmann** [comment]
Is this explicitly stated in the documentation somewhere, or do we have to clarify this?

**Comment by astedler** [comment]
I was unable to find anything in the Documentation; That is why i asked. I stumbled over a device had a _maximum_ of 320, a _factor_ of 100 and a _value_ of 5217. And my range-check failed; but it was a temperature and therefore 52.17 degree celsius is quite valid ... i guess.

**Comment by mkeuck** [comment]
The documentation now also clarifies that a factor has to be applied to the minimum, maximum and the default value, if specified.
