### ISSUE TITLE
Unclear Formula <-> Factor

### ISSUE THREAD

**Issue by astedler** [Lawo/ember-plus#54]
There is no rule for having defined both formula and factor on a parameter.
Is it allowed?
If yes, in what order do they have to be calculated? formular first or factor first?
because if formula = sin($) and factor is 15 
then:
    sin(x/15) <> sin(x)/15
as far as i know.

**Comment by mkeuck** [comment]
This is indeed not specified yet, there is not precedence defined if both properties are set. Typically, only one is provided. Is it possible for you to include the factor in the formula instead of providing an additional factor?

**Comment by astedler** [comment]
The only initention was to advise to inhibit the usage of formula and factor simultaniously on a parameter and make that clear in the manual; for it makes no sense.

**Comment by mkeuck** [comment]
That's what I wanted to find out with the question :)
We can update the documentation and indicate to use either the factor or the formula.

As far as I know there is no provider that currently uses both, so it shouln't be an issue.

**Comment by mkeuck** [comment]
If have added this rule to the latest documentation.
