### ISSUE TITLE
missing files in EmberLib.Net

### ISSUE THREAD

**Issue by Vasilich** [Lawo/ember-plus#56]
while trying to compile EmberLib.NET libraries, i see that compiler says 
```
4>CSC : error CS2001: Source file 'GlowQualifiedTemplate.cs' could not be found
4>CSC : error CS2001: Source file 'GlowTemplate.cs' could not be found
4>CSC : error CS2001: Source file 'GlowTemplateBase.cs' could not be found
```
From solution explorer i see that file `EmberLib.net\EmberLib.Glow\Documentation\Ember+ Functions.docx` is also missing in repository, though is present in project 'EmberLib.Glow'. It is just a DOCX file, but if you will fix the 3 missing CS files above, then you can commit eventually forgotten documentation :)

**Comment by mkeuck** [comment]
Hi,
sorry for that. The files, including the documentation, should be there now. Otherwise, please let us know.

**Comment by Vasilich** [comment]
yes the missing files are there, thanks.
But the solution still can't be compiled (mostly Portable part, some missing references, SpecificVersions, etc). Should i reopen this issue, or open new one?

**Comment by mkeuck** [comment]
Hi,
please try again - I fixed the references in the portable project. Unfortunately, the F# PowerPack used there is no longer available. So both, the Desktop and the Portable version now reference the portable PowerPack.

**Comment by Vasilich** [comment]
after update i just defined NO_SERIALIZATION symbol in portable.BerLib (assuming i just do not have latest toolsets for portable development installed ?), and now everything builds OK Thank you.
