### ISSUE TITLE
Where is EmberPlusView source code?

### ISSUE THREAD

**Issue by Vasilich** [Lawo/ember-plus#59]
Am i blind or the code of EmberPlusView isn't in the repository (anymore)? Was it ever published? Or is it somehow license-protected?

**Comment by KimonHoffmann** [comment]
Hi Vasilich!

The code for the EmberPlusView tool was not yet included in the repository, nor in any release. I'm deferring this question to @mkeuck, as I think he might be able to further elaborate on whether or not the code will be made available in the future.

**Comment by mkeuck** [comment]
Hi,

the code for the Viewer has never been released, because it uses some of our company-internal libraries. If you are interested in it, we may publish the part that creates the local data model/tree from the decoded data.

**Comment by Vasilich** [comment]
Yes, i am interested - it will at least help to understand the whole ember system.
Thanks in advance.
Will you then consider to publish binaries of it? Earlier (Google Code times) EmberPlusView was published as binary with every (?) release.

**Comment by KimonHoffmann** [comment]
The binary is part of every SDK version published on the releases page.
It should be contained in the `tools` subdirectory of the SDK archive.

**Comment by Vasilich** [comment]
latest release is more than 1.5 years old, and I thought that there were new versions of EmberPlusView...

**Comment by KimonHoffmann** [comment]
Not to my knowledge, but again, @mkeuck might be able to say more about that.

**Comment by KimonHoffmann** [comment]
A new version has been released and can be found on the releases page. SO I'm now closing this issue.
