### ISSUE TITLE
Missing libemer::glow::GlowParameterBase::setValue(..) overload for const char*

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Lawo/ember-plus#6]
```
As the libember::glow::Value constructor is overloaded to take a const 
std::string& and a const char*, i would suggest to overload 
libemer::glow::GlowParameterBase::setValue(..) to take a const char* to avoid 
unexpected behaviour. See the attached patch with a proposal.
```

Original issue reported on code.google.com by `nullable...@gmail.com` on 7 May 2013 at 8:42
- Blocked on: #20

Attachments:
- [Overload_setValue_const_char_pointer.patch](https://storage.googleapis.com/google-code-attachments/ember-plus/issue-6/comment-0/Overload_setValue_const_char_pointer.patch)

**Comment by mkeuck** [comment]
Since this issue will (probably) be resolved with the upcoming C++ 17 version I would like to close this entry. If this is a requirement for the 1.8 release, please reopen this issue.
