### ISSUE TITLE
Question - tinyember - VSM - Parameter access after restart

### ISSUE THREAD

**Issue by Blixthalka** [Lawo/ember-plus#65]
Hello!

This question is maybe a little bit too much about VSM and not ember+, but I hope this is the right forum to ask this question. I'm using ember+ (tinyember client) to communicate with VSM and have a question regarding how the parameters in the glow tree behaves after a VSM restart. 

When VSM has been restarted parameters with access `ReadWrite` switches access to `ReadOnly`. As indicated by the VSM gui (black text instead of blue in gadget view).  This does not happen if the parameter is assigned to a VSM button. 

It looks like this in VSM. This is before the restart, it is possible to modify both parameters. 
![before_restart](https://user-images.githubusercontent.com/7557805/30650777-18144d3a-9e24-11e7-9649-d40faaaa5756.png)

But after the restart only the one connected to a button (Video Format) is modifiable. 
![after_restart](https://user-images.githubusercontent.com/7557805/30650856-3f719aae-9e24-11e7-8c8f-94cebc0752f5.png)

It is possible to get the right access back by restarting the tinyember client, but I feel like it should not be necessary to do this. 

To replicate this:

1. Start VSM.
2. Start tinyember.
3. Create a node in tinyember and fill it with two `EnumParameters` (haven't tried with other parameters). 
4. Connect VSM to tinyember.
5. Assign one of the parameters to a button in VSM. 
6. Save and restart VSM.
7. One of the parameters is modifiable (the one connected to the button) and the other is not modifiable. 
8. Save and restart tinyember.
9. Now both parameters is modifiable. 

Is this intended behaviour? 
If it is, is it possible to make the second parameter modifiable? 

Kind regards Emil

**Comment by KimonHoffmann** [comment]
Hi Emil,

Unfortunately your question is too specific to VSM to be answered here. I suggest you contact the VSM service either by writing an email to support@lawo.com indicating that you need help with a VSM specific problem or by calling +49 611 262 390 50, which is the VSM specific support hotline as mentioned here: https://www.lawo.com/en/services/service-support/service-contact.html

Best regards,
Kimon
