### ISSUE TITLE
EmberPlusViewer crash when opening Node with multiple Parameters with EnumMap 

### ISSUE THREAD

**Issue by benoitquiniou** [Lawo/ember-plus#66]
- Using EmberPlusViewer 1.6.2
- connecting to provider with parameters having big EnumMaps attached
- traversing the tree to GetDirectory on a node containing these parameters
=> crash (see log attached)
[EmberPlusView crashed.2017-09-25 09-41.log](https://github.com/Lawo/ember-plus/files/1328630/EmberPlusView.crashed.2017-09-25.09-41.log)

**Comment by KimonHoffmann** [comment]
The most recent version fixes quite a few crashes, please investigate if this issue still applies and reopen it if necessary.

For now I'm closing it.
