### ISSUE TITLE
libember_slim has wrong 64-bit NaN value in ber.c

### ISSUE THREAD

**Issue by astedler** [Lawo/ember-plus#69]
In **ber.c** in
 **double** ber_decodeReal(**BerInput** *pIn, **int** length)

the return value for 64-bit NaN is given as 
`0x7fC0000000000000ULL`
which is wrong i guess...

NaN can be set using a uint64 cast on and set them to any number between 
`0x7FF8000000000000 and 0x7FFFFFFFFFFFFFFF`
 or 
`0xFFF8000000000000 and 0xFFFFFFFFFFFFFFFF`

I think it was just a mistake by converting from 32-bit where the range is:
`0x7FC00000 and 0x7FFFFFFF` 
or 
`0xFFC00000 and 0xFFFFFFFF`

**Comment by KimonHoffmann** [comment]
This issue has been fixed in with befea41d6745c9e1a1b685a6a4697b634c8011f0.
