### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by killater** [Lawo/ember-plus#71]
Hi guys! Been trying to reach you on G+, but no luck.
I've got a stupid question, in code examples I found this code:
          var children = _glow[GlowTags.CollectionItem][GlowTags.Node.Children];
         for(int index = 0; index < 2000; index++)
         {
            var node = new GlowNode(5 + index)
            {
               Identifier = "abc" + index,
               Description = "Hallo ich bin Node " + index,
            };
            children.Insert(node);
         }
Pretty obvious, but I'm trying to add parameters to the nodes with no luck. I've found a workaround, but I don't really like it.
So can you advice?

**Comment by KimonHoffmann** [comment]
Hi,

As the code fragment you quoted is neither C nor C++, I was wondering what example you're referring to. Can you point me to it?

Thanks in advance!

**Comment by killater** [comment]
that's the EmberPlusSimpleProvider project in the Ember.net folder of the SDK 1.6.2

**Comment by KimonHoffmann** [comment]
Unfortunately I have no experience with the .Net library, but in general you might find the
[emberplus-sharp](https://github.com/Lawo/ember-plus-sharp) library easier to grok and it has the added benefit that it comes with nice documentation, which you can find [here](http://lawo.github.io/ember-plus-sharp)

**Comment by killater** [comment]
ok, anyways, I haven't found a constructor for the Parameter object and a way to assign it to the node. Can you point me to those please? Now I'm creating a xml, that replicates the Glow XML output and then I import in with Glow_XML import, and that's not I want to do.

**Comment by stian-barnfind** [comment]
I might be off here, since I have only used the libember_slim (C version). But in that library a Parameter is not assigned to a node, but it an alternative object. So you would add the parameter as a child to a node: children.Insert(MyParameter);

The parameter should have its own Identifier and similiar properties
