### ISSUE TITLE
No method for the provider to tell the consumer that a node has been removed

### ISSUE THREAD

**Issue by stian-barnfind** [Lawo/ember-plus#80]
Let us say that your provider has dynamic configuration, due to for instance insertion of plugin-modules.

When a module is inserted, the provider can simply send the node information to the consumer, and the consumer happily knows about the new nodes. But if the module is removed, there now are some issues:

If the consumer tries to re-scan a node that no longer is present, you can not return an error. The only way a consumer can detect removal of nodes per today is to rescan the tree, and see for branches and nodes no longer present in their parents GetDir call.

**Comment by astedler** [comment]
Be careful,
a _node_ MUST NOT be removed in a running session, but you may set this _node_ to be **offline** at any time.
As long as a consumer holds the connection it is not allowde to remove it.
You may force ALL CLIENTS to rescan the tree structure by disconnecting them.
If you do not want this, yust set the node to be offline.
