### ISSUE TITLE
64 bit values

### ISSUE THREAD

**Issue by MarkBaldry** [Lawo/ember-plus#84]
It seems that the library does not handle 64 bit integers correctly when compiled as a 32 bit application (using c++), I have had to change long to __int64, is this something that really should be fixed in the library by the originator of it? I can look to do it is required.

**Comment by KimonHoffmann** [comment]
Hi Mark,

Thanks for reporting this issue! A pull request is that addresses this issue would be very welcome, thank you for the offer!

**Comment by KimonHoffmann** [comment]
This will be fixed in soon to be released C++17 variant of the library.
Please reopen this issue if a back port is required.
