### ISSUE TITLE
Faulty Ember+ Provider Matrix implementation on Lawo Nova17/Sapphire

### ISSUE THREAD

**Issue by SimonHyde-BBC** [Lawo/ember-plus#85]
I submitted the following bug report to Lawo directly, but their support department has requested that I submit it here because it's an Ember+ issue. I think they think it's a client/consumer issue, when it appears to be a server/provider issue.

I'm having issues with Ember+ control of a Saphire Mk2 (being used as a Nova17).

When a Connection request is sent to re-connect a route that is already made, the matrix returns a Connected message indicating that the original source has been de-routed and Source 0 is now routed, and leaves nothing routed to the target.

I've also noticed that even when switching a target between 2 different sources, the router delivers a Connected message indicating Source 0 is connected, before then delivering a second Connected message indicating that the requested source is routed to the target.

**Comment by KimonHoffmann** [comment]
Hello,

since this is an issue with a specific provider implementation and not a general problem with one of the libraries this is not the appropriate forum. Please refer back to the service department asking them to put you in touch with the developers of the product in question.
