### ISSUE TITLE
EmberPlusView and tools folder are missing

### ISSUE THREAD

**Issue by roelvz** [Lawo/ember-plus#88]
README.txt mentions a tools directory:
> The 'tools' directory contains prebuilt versions of 'TinyEmberPlus' and
> 'TinyEmberPlusRouter' as well as the 'EmberPlusView' utility, a generic Ember+
> consumer.

But there's no tools directory. I cannot find the EmberPlusView binary anywhere. Is it still available somewhere?

**Comment by KimonHoffmann** [comment]
This section of the README refers to the packaged releases offered under the "releases" tase here: https://github.com/Lawo/ember-plus/releases

The (non Source Code) packages provided for each release contain the aforementioned tools directory and utilities.
