### ISSUE TITLE
How to access System Matrix with Ember+ Sharp

### ISSUE THREAD

**Issue by GRieber** [Lawo/ember-plus#91]
Dear all,

is it possible to get al little example how to declare and access the system matrix in Nova29 with code of the Ember+ Sharp Project?
I am a little bit helpless at the moment :-)

Thanks for any kind of help!!

Gerhard

**Comment by mkeuck** [comment]
Hello,

Matrix support should be available in the Ember+ Sharp project, but how to access it depends on whether you use the static or the dynamic approach.

The static approach expects the entire data model to query to be declared in advance via C# classes. The dynamic approach reads whatever the provider delivers.

The following code should give an idea about how to use the dynamic model:

```
public class DynamicModel : Model.DynamicRoot<DynamicModel>
{
}
var s101Client = …;
var consumer = await Consumer<DynamicModel>.Create(s101client);

// Access children via consumer.Root.DynamicChildren property.
```

As far as I know, the root elements are queried automatically. To obtain subelements, the child's `RetrievalPolicy` property must be set to `ChildrenRetrievalPolicy.DirectOnly` (or `.All`). To receive a notification when a new node has been received, it is required to subscribe to the observable collection provided by the `INode.Children` property. Children are all of type IElement, and a type cast is required to check whether the underlying type is an `INode`, an `IMatrix` or something else.

I hope this helps as starting point. Some more information can be found here:
[Create a local copy of the provider database](http://lawo.github.io/ember-plus-sharp/html/f6285c3c-ef54-453e-90ad-5546ec1a7a1d.htm)

**Comment by GRieber** [comment]
Hello,

Thank you very much for your answer.
What I forgot in my request is the fact, that I am a little bit common in programming EmbER+ consumers with the Ember+ Sharp project. Some of the consumers I wrote using the static, some others using the  dynamic approach.
In this case I started to use the static way. The first classes until "`Matrix Params`" work very well. But when I reach the point, where the class for the "`System Matrix`" should be declared, I stand in front of a big and tall wall :-(

```
 Private NotInheritable Class Nova29Root
        Inherits Root(Of Nova29Root)

        Friend Property Nova29 As Nova29

    End Class

    Private NotInheritable Class Nova29
        Inherits FieldNode(Of Nova29)

        Friend Property Matrices As Matrices

    End Class

    Private NotInheritable Class Matrices
        Inherits FieldNode(Of Matrices)

        <Element(Identifier:="Matrix Params")>
        Friend Property Matrix_Params As Matrix_Params

        <Element(Identifier:="System Matrix")>
        Friend Property System_Matrix As .........

    End Class
```

As you can see, I write my code in VB.NET. I am able to read C# but I cannot write in this language. But this was no problem during the time I learned to use the Ember+ Sharp project :-)

So, could you please be so kind to give me a little example how to declare my class(es) to reach the `System Matrix` in Nova 29?

This would be very nice!

Kind regards

Gerhard

**Comment by mkeuck** [comment]
Ok, that information changes everything :) I will have to investigate this myself since I am neither the author nor a user of that library. But I will post a reply as soon as possible.

I think you could specify a `DynamicMatrix<T>`, where T is a type deriving from `DynamicMatrix<T>`. The other option would be the Matrix, but I also have to find out what `TMostDerived` expects here :) It looks like it requires the entire subtree structure, which contains labels, target- and source-parameters, and connection parameters. 

Best regards,
Marius

**Comment by GRieber** [comment]
Hello Marius,
this exactly what my question means :-)

Thank you so much!!

Best regards
Gerhard

**Comment by mkeuck** [comment]
Hello Gerhard,

I now managed to access a matrix provided by the TinyEmberPlusRouter tool. It seems that the generic type is only required if the matrix contains subnodes itself, which is sometimes the case for labels or parameters. These can then be accessed via a custom class declaring the structure.

The example I wrote accesses an n:n matrix and performs one crosspoint connection. The tree can be seen on the image and the attached zip file contains the sample program.

I hope that helps,
Marius

![TinyEmberPlusRouterTree](https://user-images.githubusercontent.com/12731500/54981608-ff6dd980-4fa8-11e9-89e7-1dc3639344e8.PNG)

[ConsumerSample.zip](https://github.com/Lawo/ember-plus/files/3007149/ConsumerSample.zip)

**Comment by GRieber** [comment]
Hello Marius,

thank you for your reply!
Unfortunately I'm still unable to access the matrix.
Please see my adaption of your sample into VB to contact the Nova29 device.

```
NotInheritable Class Nova29Root
        Inherits Root(Of Nova29Root)

        <Element(Identifier:="Nova29")>
        Public Property Nova29 As Nova29

    End Class

    NotInheritable Class Nova29
        Inherits FieldNode(Of Nova29)

        <Element(Identifier:="Matrices")>
        Public Property Matrices As Matrices

        <Element(Identifier:="identity")>
        Public Property Identity As Identity

    End Class

    NotInheritable Class Matrices
        Inherits FieldNode(Of Matrices)

        <Element(Identifier:="System Matrix")>
        Public Property System_Matrix As NToNMatrix

        <Element(Identifier:="Matrix Labels")>
        Public Property Labels As LabelsNode

        <Element(Identifier:="Matrix Params")>
        Public Property Params As LabelsNode

    End Class


    NotInheritable Class LabelsNode
        Inherits FieldNode(Of LabelsNode)

        <Element(Identifier:="targets")>
        Public Property Targets As CollectionNode(Of StringParameter)

        <Element(Identifier:="sources")>
        Public Property Sources As CollectionNode(Of StringParameter)

    End Class

    NotInheritable Class NToNMatrix
        Inherits DynamicMatrix(Of NToNMatrix)
    End Class


    NotInheritable Class Identity
        Inherits FieldNode(Of Identity)

        <Element(Identifier:="product")>
        Public Property Product As IParameter

    End Class
```

When the program is started, I get the following error message when the `create.async` timeout is reached:


![image](https://user-images.githubusercontent.com/14273314/55061068-2395ed00-5073-11e9-858e-55658cd9abb3.png)

When I remove the element `Matrices `out of the `Nova29 `- class, there is no error and I get the result of `Identity/Product` = "Nova29".
Therefore my consumer seems to work fine...

Do you know, where my mistake is? :-)

Many thanks an kind regards.

Gerhard

**Comment by mkeuck** [comment]
Hello Gerhard,
it looks correct so far. Are you sure that you are using the node identifiers (e.g. "System Matrix") in the Element attribute, and not the description string?

I may have access to a Nova29 tomorrow, I can then test it with a real device as well which should help to find out whats going wrong.

Best regards,
Marius

**Comment by GRieber** [comment]
...these are good news :-)
Yes, I use the identifiers as shown in the Ember+ Viewer.
Let's see what your tests will find out.

Best regards,

Gerhard

**Comment by mkeuck** [comment]
I was now able to reproduce this issue and I think it is caused by the fact that the Ember Plus Sharp Lib sends several `GetDirectory` requests in a single message. This is not explicitly forbidden, but the Nova 29 only supports single requests due to limited hardware resources, as far as I know.

When I removed the identity node from the class declaring it, the matrix could be loaded correctly.

It seems that there is no way yet to  tell the library to send requests in a separate packets, so the only workaround right now is to use the dynamic methods to query the matrix - if several nodes having the same parent are needed. You can then use the `Direct` `ChildrenRetrievalPolicy` and a call to `SendAsync` after accessing a node. 

There may be a possibility to change the behavior of the library, but I will have to investigate this first.

**Comment by GRieber** [comment]
Dear Marius,

this was a great success!
When I removed the "identity" - node and further the "Matrix Labels" and "Matrix Params" - nodes, I could access the System Matrix. This will fullfill my needs. I only want to check and set connections and react on changes.

So, here are my next questions:
When I declare

`Dim matrix as IMatrix`
`AddHandler matrix.PropertyChanged, AddressOf OnMatrixChanged`

nothing happens in my app while I set and reset crosspoints in EmberViewer and in NovaConnect.

And - second question - how do I access the crosspoints I whish to monitor or to switch?
I think, a try-and-error-approach would lead me to the target, but with your help it could be quite easier :-)

Thank you very much!!

Best regards

Gerhard

**Comment by mkeuck** [comment]
Hello Gerhard,
observing crosspoints requires to subscribe to every target's `ObservableCollection `separately. The matrix object has a `Connections `property, which contains one entry for each target, accessed by its index. You can then access that collection and read the status. Or, you can modify the collection and send the changes.

```
var matrix = consumer.Root....Matrix;

if (matrix.Connections.TryGetValue(0, out var sources))
{
    // sources now contains the sources of target 0.
    // Add source 3 to connect it.
    sources.Add(3);

    // Send the changes.
    await consumer.SendAsync();
}
```

Best regards,
Marius

**Comment by GRieber** [comment]
Hello Marius,

thank you very much!
This works perfectly :-)

There remains only one issue with the `matrix.PropertyChanged` - event.
Whenever I change a crosspoint - may be by Ember+Viewer or by NovaConnect, nothing happens, no event is fired.
Is there anything I have to do more?

Thanks again and best regards,
Gerhard

**Comment by mkeuck** [comment]
Hello Gerhard,

can you please subscribe to the `CollectionChanged` event of the target's `ObservableCollection`? There should be an event notification when a crosspoint changes. Unfortunately, this must be done for every target you are interested in.

Best regards,
Marius

**Comment by GRieber** [comment]
Hello Marius,
you've got 100 points!
Everything works fine!

Thank you very much for your patience and your great help!

Kind regards
Gerhard

**Comment by mkeuck** [comment]
Hello Gerhard,
I am glad I could help.

Best regards,
Marius
