### ISSUE TITLE
Malformed integer encodings in EmberPlusView 2.4

### ISSUE THREAD

**Issue by jorgen-gh** [Lawo/ember-plus#96]
The initial getDirectory issued by Ember+ Viewer 2.4 has the following form:
60 80 6b 80 a0 80 62 80 a0 04 02 02 **00 20** a1 04 02 02 **ff ff** 00 00 00 00 00 00 00 00

where I have maked the two integers in question as bold. The first is the command type 32 = getDirectory, and the second is the field mask -1 = all. The first nine bits of the first integer are all zero, and the first nine bits of the second integer are all one.

The Ember+ documentation (and the ASN.1 spec) clearly states:
_Special care must be taken by the encoder to comply to rule [X.690 8.3.2]: the first 9 bits of the encoded integer value must not be the same._
Moreover, an example of how to encode -1 is listed in the ember+ documentation stating it should be "FF". 

EmberPlusView 1.6 does not have this problem.

**Comment by mkeuck** [comment]
Hello,
I wanted to take a closer look into this today, but unfortunately I have to postpone it. It indeed looks like a subtle encoding error.
I am going to post an update about this as soon as possible, probably beginning of next week.

Best regards,
Marius

**Comment by mkeuck** [comment]
It looks like this error has only been introduced in the Ember+ Viewer, which uses a separate C# implementation of the Ember+ library. We are going to fix this within the next days and release a new version.

**Comment by mkeuck** [comment]
We have fixed this encoding issue in the Viewer and will publish a new release beginning of next week. The libraries in this repository should not be affected by this issue.

**Comment by KimonHoffmann** [comment]
Fixed with EmberPlus Viewer v2.40.0.24 available on the releases page.
